##
POST http://localhost:8080/comment/7
Content-Type: application/json

{
"comment":"This is really amazing, i can't believe its true",
"commentor":"Saiteja"
}


###
GET http://localhost:8080/comment+/2
###
GET http://localhost:8080/comment-/2
