##
POST http://localhost:8080/comment/12
Content-Type: application/json

{
"comment":"test",
"commnetedBy":"saitea"
}


###
GET http://localhost:8080/comment+/2
###
GET http://localhost:8080/comment-/2
