
//CREATE
###
POST http://localhost:8080/post
Content-Type: application/json

{
  "title": "abcd",
  "content": "saitejakda@gmail.com",
  "description": "abcdef",
  "categoryId": "1"
}
###
//READ
###
GET http://localhost:8080/post
###
GET http://localhost:8080/post/4
###
GET http://localhost:8080/post/count
###
GET http://localhost:8080/post/genres/News
###
GET http://localhost:8080/post/type/Trending
###
GET http://localhost:8080h/like/4
###
//UPDATE
###
PUT http://localhost:8080/post/2
Content-Type: application/json

{
  "title": "abc",
  "content": "saitejakda@gmail.com",
  "description": "abcde",
  "tags": [
    {
      "name": "new"
    }
  ],
  "categoryId": "1"
}
###
//DELETE
###
DELETE http://localhost:8080/post/2
