
//CREATE
###
POST http://localhost:8080/post
Content-Type: application/json

{
  "title": "abcd",
  "content": "saitejakda@gmail.com",
  "description": "abcdef",
  "categoryId": "1"
}
###
//READ
###
GET http://localhost:8080/post
###
GET http://localhost:8080/post/24
###
GET http://localhost:8080/post/count
###
GET http://localhost:8080/post/genres/News
###
GET http://localhost:8080/post/type/Trending
###
GET http://localhost:8080/like/24
###
GET http://localhost:8080/post/comments/count/8
###
GET  http://localhost:8080/posts/type/Featured
###
//UPDATE
###
PUT http://localhost:8080/post/24
Content-Type: application/json

{
  "title": "abc",
  "content": "saitejakda@gmail.com",
  "description": "abcde",
  "categoryId": "1"
}
###
//DELETE
###
DELETE http://localhost:8080/post/2
