###
POST https://teluguphantom.herokuapp.com/admin/category
Content-Type: application/json

{
    "name": "Events"
}
###
//        String[] Genre = {"Music", "Entertainment", "Health", "Technology", "Events", "Facts"};

###

POST https://athenanetworks.herokuapp.com/category
Content-Type: application/json

{
    "name": "Tv Series"
}



###
GET https://teluguphantom.herokuapp.com/category

###
DELETE http://localhost:8080/category/2

###
PUT http://localhost:8080/category/3
Content-Type: application/json

{
    "name": "PacMan Bullshit"
}

