##
POST http://localhost:5000/comment/25
Content-Type: application/json

{
"comment":"This Show is really amazing, Mind blowing thriller and best amoung series on Netflix",
"commentor":"Saiteja Konda"
}

###
DELETE http://teluguphantom.ap-south-1.elasticbeanstalk.com/admin/comment/2

###
GET http://localhost:8080/comment-/7

###
DELETE  http://localhost:5000/admin/comment/4
