
//CREATE
###
POST http://localhost:8080/post
Content-Type: application/json

{
    "title": "abcde",
    "content": "Labore amet doloribus ex eos sequi asperiores dolor blanditiis omnis est quia amet iusto facere.",
    "description": "Labore amet doloribus ex eos sequi asperiores dolor blanditiis omnis est quia amet iusto facere.",
    "categoryId": "1",
    "type": "Latest"
}
###
//READ
###
GET http://localhost:8080/post
###
GET http://localhost:8080/post/1
###
GET http://localhost:8080/post/count
###
GET http://localhost:8080/post/genres/News
###
GET http://localhost:8080/post/type/Trending
###
GET http://localhost:8080/like/2
###
GET http://localhost:8080/post/comments/count/8
###
GET  http://localhost:8080/posts/type/Featured
###
//UPDATE
###
PUT http://localhost:8080/post/2
Content-Type: application/json

{
  "title": "abc",
  "content": "saitejakda@gmail.com",
  "description": "abcde",
  "categoryId": "1"
}
###
//DELETE
###
DELETE http://localhost:8080/post/1
