###
POST http://localhost:8080/reply/1
Content-Type: application/json

{
    "reply": "Yes i just wateched couple of season, its awesome, i cant wait to watch season 3",
    "repliedBy": "Deno"
}

###
GET http://localhost:8080/reply+/3

###
GET http://localhost:8080/reply-/2
