###
POST http://localhost:8080/subscribers
Content-Type: application/json

{
    "name": "saiteja",
    "email": "kondasaitej@gmail.com"
}

###

###
GET http://localhost:8080/admin/subscribers

###
###
